$(document).ready(function(){
    $('.owl-carousel').owlCarousel({
        loop:true,
        margin: 15,
        nav:true,
        responsive:{
            0:{
                items:1,
                nav:false,
                autoplay:true,
                autoplayTimeout:6000,
                autoplayHoverPause:true
            },
            600:{
                items:1,
                margin:0,
                nav:true
            },
            1000:{
                items:2,
                nav:true,
            }
        }
    })
});